### ISSUE TITLE
[Compatibility] Crashes with earlier version Qt library

### ISSUE THREAD

**Issue by marsCatXdu** [Reverier-Xu/typrua#1]
Crashes with qt library earlier than 5.15. 
```
$ ./TypRua
QtWebEngine::initialize() must be called after the construction of the application object.
Aborted
```
Tested result:

|       | Fedora 35 aarch64, qt 5.15 | UnionTechOS Professional x86_64, qt5.11 | UnionTechOS Server E aarch64, qt5.11 |
| ----- | -------------------------- | --------------------------------------- | ------------------------------------ |
| build | Pass                       | Pass                                    | Pass                                 |
| run   | Pass                       | Fail                                    | Fail                                 |

**Comment by Reverier-Xu** [comment]
maybe a Qt bug here: https://bugreports.qt.io/browse/QTBUG-80912

**Comment by Reverier-Xu** [comment]
Another problem is that DragHandler only supports QtQuick 2.12+ which is provided by Qt 5.12+, i'll try to use native window instead of customized one.

https://doc.qt.io/qt-5/qml-qtquick-draghandler.html

**Comment by marsCatXdu** [comment]
> Another problem is that DragHandler only supports QtQuick 2.12+ which is provided by Qt 5.12+, i'll try to use native window instead of customized one.
> 
> https://doc.qt.io/qt-5/qml-qtquick-draghandler.html

May be a good idea. Native window will also get a better wayland compatibility. Current custom window runs on wayland with a bad look.

Add support for qt 5.11 may be better, 5.11 was used by debian10 and its downstream OS like ubuntu 20

**Comment by Reverier-Xu** [comment]
seems ok.
![image](https://user-images.githubusercontent.com/41937333/143984573-b0c48e1f-a395-4566-841c-7bcf40d1825c.png)
