### ISSUE TITLE
[Compatibility] Qt.labs.platform not exist on qt 5.11

### ISSUE THREAD

**Issue by marsCatXdu** [Reverier-Xu/typrua#3]
Qt.labs.platform not exist on qt 5.11 , reference:
https://doc.qt.io/archives/qt-5.11/qtquickcontrols2-index.html

Run failed on OS with qt 5.11, log :
```
lijingwei@lijingwei-PC:~/typrua/build/bin$ ./TypRua 
QQmlApplicationEngine failed to load component
qrc:/views/MainWindow.qml:4 module "Qt.labs.platform" version 1.1 is not installed
```

Downgrade the version to 1.0 can solve this.

**Comment by Reverier-Xu** [comment]
ok... QtQuick module's version is always different with Qt, that makes me confused.

**Comment by marsCatXdu** [comment]
> ok... QtQuick module's version is always different with Qt, that makes me confused.

https://doc.qt.io/archives/qt-5.11   keeps historical documents. Version mappings can be found here.
